# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query_SDF_network.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17query_SDF_network.proto\x12\x12SDF_query_protocol\"T\n\x08QueryMsg\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01t\x18\x04 \x01(\x02\x12\x1c\n\x14latent_code_elements\x18\x05 \x03(\x02\"K\n\x08SDFvalue\x12+\n\x05input\x18\x01 \x01(\x0b\x32\x1c.SDF_query_protocol.QueryMsg\x12\x12\n\nsdf_output\x18\x02 \x01(\x02\x32\xa8\x01\n\x0b\x43lientToSDF\x12H\n\x08queryOne\x12\x1c.SDF_query_protocol.QueryMsg\x1a\x1c.SDF_query_protocol.SDFvalue\"\x00\x12O\n\x0bqueryStream\x12\x1c.SDF_query_protocol.QueryMsg\x1a\x1c.SDF_query_protocol.SDFvalue\"\x00(\x01\x30\x01\x42&\n$cz.it4i.ulman.transfers.sdf.protocolb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_SDF_network_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$cz.it4i.ulman.transfers.sdf.protocol'
  _QUERYMSG._serialized_start=47
  _QUERYMSG._serialized_end=131
  _SDFVALUE._serialized_start=133
  _SDFVALUE._serialized_end=208
  _CLIENTTOSDF._serialized_start=211
  _CLIENTTOSDF._serialized_end=379
# @@protoc_insertion_point(module_scope)
