# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query_SDF_network.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17query_SDF_network.proto\x12\x12SDF_query_protocol\"T\n\x08QueryMsg\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01t\x18\x04 \x01(\x02\x12\x1c\n\x14latent_code_elements\x18\x05 \x03(\x02\"K\n\x08SDFvalue\x12+\n\x05input\x18\x01 \x01(\x0b\x32\x1c.SDF_query_protocol.QueryMsg\x12\x12\n\nsdf_output\x18\x02 \x01(\x02\"\xd8\x01\n\x08QueryBox\x12\r\n\x05x_min\x18\x01 \x01(\x02\x12\r\n\x05x_max\x18\x02 \x01(\x02\x12\r\n\x05y_min\x18\x03 \x01(\x02\x12\r\n\x05y_max\x18\x04 \x01(\x02\x12\r\n\x05z_min\x18\x05 \x01(\x02\x12\r\n\x05z_max\x18\x06 \x01(\x02\x12\t\n\x01t\x18\x07 \x01(\x02\x12\x17\n\rxyz_max_delta\x18\x08 \x01(\x02H\x00\x12 \n\x16xyz_intermediate_steps\x18\t \x01(\rH\x00\x12\x1c\n\x14latent_code_elements\x18\n \x03(\x02\x42\x0e\n\x0cxyz_stepping\"\xf4\x01\n\x0cSDFboxValues\x12\x0f\n\x07x_start\x18\x01 \x01(\x02\x12\x0f\n\x07x_delta\x18\x02 \x01(\x02\x12\x14\n\x0cx_num_values\x18\x03 \x01(\r\x12\x0f\n\x07y_start\x18\x04 \x01(\x02\x12\x0f\n\x07y_delta\x18\x05 \x01(\x02\x12\x14\n\x0cy_num_values\x18\x06 \x01(\r\x12\x0f\n\x07z_start\x18\x07 \x01(\x02\x12\x0f\n\x07z_delta\x18\x08 \x01(\x02\x12\x14\n\x0cz_num_values\x18\t \x01(\r\x12\t\n\x01t\x18\n \x01(\x02\x12\x13\n\x0bsdf_outputs\x18\x0b \x03(\x02\x12\x1c\n\x14latent_code_elements\x18\x0c \x03(\x02\x32\xf6\x01\n\x0b\x43lientToSDF\x12H\n\x08queryOne\x12\x1c.SDF_query_protocol.QueryMsg\x1a\x1c.SDF_query_protocol.SDFvalue\"\x00\x12O\n\x0bqueryStream\x12\x1c.SDF_query_protocol.QueryMsg\x1a\x1c.SDF_query_protocol.SDFvalue\"\x00(\x01\x30\x01\x12L\n\x08queryBox\x12\x1c.SDF_query_protocol.QueryBox\x1a .SDF_query_protocol.SDFboxValues\"\x00\x42&\n$cz.it4i.ulman.transfers.sdf.protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_SDF_network_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$cz.it4i.ulman.transfers.sdf.protocol'
  _globals['_QUERYMSG']._serialized_start=47
  _globals['_QUERYMSG']._serialized_end=131
  _globals['_SDFVALUE']._serialized_start=133
  _globals['_SDFVALUE']._serialized_end=208
  _globals['_QUERYBOX']._serialized_start=211
  _globals['_QUERYBOX']._serialized_end=427
  _globals['_SDFBOXVALUES']._serialized_start=430
  _globals['_SDFBOXVALUES']._serialized_end=674
  _globals['_CLIENTTOSDF']._serialized_start=677
  _globals['_CLIENTTOSDF']._serialized_end=923
# @@protoc_insertion_point(module_scope)
